import type { Trip, Expense, Activity } from '@/types';

export const mockTrips: Trip[] = [
  {
    id: 'trip-1',
    destination: '云南大理',
    startDate: '2026-07-10',
    endDate: '2026-07-15',
    travelers: 2,
    budgetLevel: 'comfortable',
    estimatedBudget: {
      transportation: 1200,
      accommodation: 1440,
      food: 960,
      tickets: 720,
      shopping: 240,
      other: 240,
    },
    status: 'planning',
    createdAt: '2026-06-01T10:00:00Z',
    updatedAt: '2026-06-15T14:30:00Z',
  },
  {
    id: 'trip-2',
    destination: '日本东京',
    startDate: '2026-08-01',
    endDate: '2026-08-07',
    travelers: 2,
    budgetLevel: 'luxury',
    estimatedBudget: {
      transportation: 5600,
      accommodation: 6720,
      food: 4480,
      tickets: 3360,
      shopping: 1120,
      other: 1120,
    },
    status: 'planning',
    createdAt: '2026-05-20T09:00:00Z',
    updatedAt: '2026-06-10T16:45:00Z',
  },
  {
    id: 'trip-3',
    destination: '成都',
    startDate: '2026-06-20',
    endDate: '2026-06-23',
    travelers: 3,
    budgetLevel: 'economy',
    estimatedBudget: {
      transportation: 900,
      accommodation: 1080,
      food: 720,
      tickets: 540,
      shopping: 180,
      other: 180,
    },
    status: 'ongoing',
    createdAt: '2026-06-01T10:00:00Z',
    updatedAt: '2026-06-18T12:00:00Z',
  },
];

export const mockExpenses: Expense[] = [
  {
    id: 'exp-1',
    tripId: 'trip-3',
    category: 'transportation',
    description: '高铁票',
    amount: 897,
    date: '2026-06-20',
    note: '三人往返',
  },
  {
    id: 'exp-2',
    tripId: 'trip-3',
    category: 'accommodation',
    description: '酒店住宿',
    amount: 1200,
    date: '2026-06-20',
    note: '两晚家庭房',
  },
  {
    id: 'exp-3',
    tripId: 'trip-3',
    category: 'food',
    description: '火锅晚餐',
    amount: 450,
    date: '2026-06-20',
  },
  {
    id: 'exp-4',
    tripId: 'trip-3',
    category: 'tickets',
    description: '大熊猫基地门票',
    amount: 165,
    date: '2026-06-21',
    note: '三人',
  },
  {
    id: 'exp-5',
    tripId: 'trip-3',
    category: 'food',
    description: '小吃',
    amount: 200,
    date: '2026-06-21',
    note: '锦里古街',
  },
];

export const mockActivities: Activity[] = [
  {
    id: 'act-1',
    tripId: 'trip-3',
    date: '2026-06-20',
    time: '08:00',
    location: '高铁站',
    title: '出发前往成都',
    description: '乘坐G307次高铁',
    type: 'transportation',
    sortOrder: 1,
  },
  {
    id: 'act-2',
    tripId: 'trip-3',
    date: '2026-06-20',
    time: '12:30',
    location: '酒店',
    title: '办理入住',
    description: '春熙路附近酒店',
    type: 'other',
    sortOrder: 2,
  },
  {
    id: 'act-3',
    tripId: 'trip-3',
    date: '2026-06-20',
    time: '14:00',
    location: '锦里古街',
    title: '游览锦里',
    description: '逛古街，品小吃',
    type: 'sightseeing',
    sortOrder: 3,
  },
  {
    id: 'act-4',
    tripId: 'trip-3',
    date: '2026-06-20',
    time: '18:30',
    location: '蜀大侠火锅',
    title: '火锅晚餐',
    description: '正宗成都火锅',
    type: 'food',
    sortOrder: 4,
  },
  {
    id: 'act-5',
    tripId: 'trip-3',
    date: '2026-06-21',
    time: '08:30',
    location: '大熊猫繁育研究基地',
    title: '看大熊猫',
    description: '早上熊猫最活跃',
    type: 'sightseeing',
    note: '记得提前预约',
    sortOrder: 1,
  },
  {
    id: 'act-6',
    tripId: 'trip-3',
    date: '2026-06-21',
    time: '13:00',
    location: '宽窄巷子',
    title: '宽窄巷子午餐',
    description: '体验成都慢生活',
    type: 'food',
    sortOrder: 2,
  },
  {
    id: 'act-7',
    tripId: 'trip-1',
    date: '2026-07-10',
    time: '09:00',
    location: '大理站',
    title: '抵达大理',
    description: '乘坐动车前往',
    type: 'transportation',
    sortOrder: 1,
  },
  {
    id: 'act-8',
    tripId: 'trip-1',
    date: '2026-07-10',
    time: '12:00',
    location: '大理古城',
    title: '古城漫步',
    description: '逛人民路、洋人街',
    type: 'sightseeing',
    sortOrder: 2,
  },
  {
    id: 'act-9',
    tripId: 'trip-1',
    date: '2026-07-11',
    time: '08:00',
    location: '洱海',
    title: '环洱海骑行',
    description: '租电动车环游洱海',
    type: 'sightseeing',
    note: '注意防晒',
    sortOrder: 1,
  },
];

export function getMockData() {
  return {
    trips: mockTrips,
    expenses: mockExpenses,
    activities: mockActivities,
  };
}
